import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useState } from "react";

export type Language = "en" | "sw";

interface I18nContextType {
  lang: Language;
  setLang: (l: Language) => Promise<void>;
  t: (key: string) => string;
}

const STORAGE_KEY = "@farmguard_language";

const translations: Record<Language, Record<string, string>> = {
  en: {
    "welcome.back": "Welcome back",
    "app.name": "Farmguard",
    "ai.diagnosis": "AI-Powered Diagnosis",
    "scan.farm": "Scan Your Farm",
    "scan.desc": "Take a photo or describe symptoms to identify diseases, pests, and conditions",
    "start.diagnosis": "Start Diagnosis",
    "total.scans": "Total Scans",
    "high.risk": "High Risk",
    "critical": "Critical",
    "quick.diagnose": "Quick Diagnose",
    "crop.issue": "Crop Issue",
    "crop.desc": "Diseases, pests, deficiencies",
    "livestock.issue": "Livestock Issue",
    "livestock.desc": "Health conditions, injuries",
    "recent.diagnoses": "Recent Diagnoses",
    "see.all": "See all",
    "no.diagnoses": "No diagnoses yet",
    "no.diagnoses.desc": "Tap 'Start Diagnosis' to scan your first crop or livestock",
    "new.diagnosis": "New Diagnosis",
    "photo.desc": "Photo + description gives the best results",
    "what.diagnosing": "What are you diagnosing?",
    "crop": "Crop",
    "livestock": "Livestock",
    "crop.type": "Crop type (optional)",
    "livestock.type": "Livestock type (optional)",
    "photo.optional": "Photo (optional but recommended)",
    "camera": "Camera",
    "gallery": "Gallery",
    "describe.problem": "Describe the problem (optional)",
    "diagnose.ai": "Diagnose with AI",
    "diagnose.analyzing": "Analyzing...",
    "diagnose.disclaimer": "Powered by Claude AI. Results are advisory \u2014 consult an agricultural expert for critical issues.",
    "market.title": "Farmguard Market",
    "market.subtitle": "Fresh produce, direct from farmers",
    "shop": "Shop",
    "my.farm": "My Farm",
    "search": "Search produce, location...",
    "register.farmer": "Register as Farmer",
    "sell.text": "Sell on Farmguard Market",
    "sell.desc": "Register your farm and start listing your fresh produce, livestock, and more to reach buyers near you.",
    "grow.planner": "Grow Planner",
    "moon.planting": "Moon-aware planting calendar for your season",
    "moon.today": "Moon Today",
    "upcoming.moon": "Upcoming Moon Events",
    "your.location": "Your Location",
    "use.my.location": "Use My Location",
    "detecting": "Detecting...",
    "enter.manually": "Enter Manually",
    "save": "Save",
    "cancel": "Cancel",
    "my.land": "My Land",
    "land.desc": "Design your plot, place plants, track health",
    "create.plot": "Create Plot",
    "agro.stores": "Agro Stores",
    "no.plots": "No land plots yet",
    "no.plots.desc": "Create a digital map of your farm. Draw the plot shape, drop plant markers, and track their health over time.",
    "create.first.plot": "Create First Plot",
    "history": "History",
    "no.history": "No diagnoses yet",
    "no.history.desc": "Your diagnosis history will appear here",
    "all": "All",
    "crops": "Crops",
    "livestock2": "Livestock",
    "clear.history": "Clear History",
    "clear.history.confirm": "Are you sure you want to delete all diagnosis records?",
    "delete.all.confirm": "Are you sure you want to delete all diagnosis records?",
    "no.filter.diagnoses": "No diagnoses in this category",
    "history.appears.here": "Your diagnosis history will appear here",
    "land.subtitle": "Design your plot, place plants, track health",
    "grow.plan.reminder": "Grow Plan Reminder",
    "plant": "Plant",
    "starting.today": "starting today",
    "error": "Error",
    "grow.plan.error": "Could not generate grow plan. Please try again.",
    "delete.all": "Delete All",
    "condition": "Condition",
    "severity": "Severity",
    "confidence": "Confidence",
    "summary": "Summary",
    "symptoms": "Symptoms",
    "possible.causes": "Possible Causes",
    "treatments": "Treatments",
    "prevention": "Prevention",
    "urgency": "Urgency",
    "your.description": "Your Description",
    "new.diagnosis2": "New Diagnosis",
    "delete.diagnosis": "Delete Diagnosis",
    "delete.confirm": "Remove this diagnosis from your history?",
    "delete": "Delete",
    "weather": "Weather",
    "today": "Today",
    "tomorrow": "Tomorrow",
    "humidity": "Humidity",
    "wind": "Wind",
    "rain.chance": "Rain Chance",
    "uv.index": "UV Index",
    "farming.advice": "Farming Advice",
    "share": "Share",
    "share.via": "Share via",
    "copy": "Copy",
    "copied": "Copied to clipboard",
    "whatsapp": "WhatsApp",
    "sms": "SMS",
    "share.diagnosis": "Share Diagnosis",
    "share.text": "Check this diagnosis on Farmguard:",
    "settings": "Settings",
    "language": "Language",
    "english": "English",
    "swahili": "Swahili",
    "notifications": "Notifications",
    "enable.notifications": "Enable Notifications",
    "notification.reminders": "Grow Plan Reminders",
    "notification.moon": "Moon Events",
    "notification.diagnosis": "Diagnosis Follow-ups",
    "near.me": "Near Me",
    "sort.by": "Sort by",
    "price.low.high": "Price: Low to High",
    "price.high.low": "Price: High to Low",
    "distance": "Distance",
    "newest": "Newest",
    "crop.database": "Crop Database",
    "search.crops": "Search crops...",
    "crop.details": "Crop Details",
    "days.to.maturity": "Days to Maturity",
    "spacing": "Spacing",
    "water.needs": "Water Needs",
    "sun.needs": "Sun Needs",
    "planting.depth": "Planting Depth",
    "seasons": "Seasons",
    "regions": "Regions",
    "companion.plants": "Companion Plants",
    "common.pests": "Common Pests",
    "offline.saved": "Saved offline",
    "no.connection": "No internet connection",
    "retry": "Retry",
    "offline.message": "You're offline. Showing cached data.",
    "dismiss": "Dismiss",
    "watering": "Watering",
    "weeding": "Weeding",
    "fertilizing": "Fertilizing",
    "harvesting": "Harvesting",
    "pruning": "Pruning",
    "spraying": "Spraying",
    "soil.prep": "Soil Preparation",
    "sowing": "Sowing",
    "germination": "Germination",
    "vegetative": "Vegetative Growth",
    "flowering": "Flowering",
    "fruiting": "Fruiting",
  },
  sw: {
    "welcome.back": "Karibu tena",
    "app.name": "Farmguard",
    "ai.diagnosis": "Uchunguzi wa AI",
    "scan.farm": "Chunguza Shamba Lako",
    "scan.desc": "Piga picha au elezea dalili za magonjwa, wadudu na hali",
    "start.diagnosis": "Anza Uchunguzi",
    "total.scans": "Uchunguzi Wote",
    "high.risk": "Hatari Kubwa",
    "critical": "Muhimu",
    "quick.diagnose": "Uchunguzi wa Haraka",
    "crop.issue": "Mazao",
    "crop.desc": "Magonjwa, wadudu, ukosefu wa virutubisho",
    "livestock.issue": "Mifugo",
    "livestock.desc": "Hali za afya, majeraha",
    "recent.diagnoses": "Uchunguzi wa Hivi Karibuni",
    "see.all": "Tazama zote",
    "no.diagnoses": "Hakuna uchunguzi bado",
    "no.diagnoses.desc": "Gusa 'Anza Uchunguzi' kuchunguza mazao au mifugo wako wa kwanza",
    "new.diagnosis": "Uchunguzi Mpya",
    "photo.desc": "Picha + maelezo yanatoa matokeo bora",
    "what.diagnosing": "Unachunguza nini?",
    "crop": "Mazao",
    "livestock": "Mifugo",
    "crop.type": "Aina ya Mazao (si lazima)",
    "livestock.type": "Aina ya Mifugo (si lazima)",
    "photo.optional": "Picha (si lazima lakini inashauriwa)",
    "camera": "Kamera",
    "gallery": "Maktaba",
    "describe.problem": "Elezea tatizo (si lazima)",
    "diagnose.ai": "Chunguza kwa AI",
    "diagnose.analyzing": "Inachunguza...",
    "diagnose.disclaimer": "Inaendeshwa na Claude AI. Matokeo ni ya ushauri \u2014 tafuta mtaalamu wa kilimo kwa masuala muhimu.",
    "market.title": "Soko la Farmguard",
    "market.subtitle": "Chakula cha moja kwa moja kutoka kwa wakulima",
    "shop": "Soko",
    "my.farm": "Shamba Langu",
    "search": "Tafuta mazao, eneo...",
    "register.farmer": "Jiandikishe kama Mkulima",
    "sell.text": "Uza kwenye Soko la Farmguard",
    "sell.desc": "Jiandikishe shamba lako na uanze kuweka mazao yako, mifugo, na zaidi ili kuwafikia wauzaji karibu nawe.",
    "grow.planner": "Mpangilio wa Ukuaji",
    "moon.planting": "Kalenda ya kupanda kwa mwezi",
    "moon.today": "Mwezi wa Leo",
    "upcoming.moon": "Matukio ya Mwezi Yajayo",
    "your.location": "Eneo Lako",
    "use.my.location": "Tumia Eneo Langu",
    "detecting": "Inagundua...",
    "enter.manually": "Weka kwa Mikono",
    "save": "Hifadhi",
    "cancel": "Ghairi",
    "my.land": "Ardhi Yangu",
    "land.desc": "Panga shamba, weka mimea, fuatilia afya",
    "create.plot": "Unda Kiwanja",
    "agro.stores": "Maduka ya Kilimo",
    "no.plots": "Hakuna viwanja bado",
    "no.plots.desc": "Tengeneza ramani ya kidigitali ya shamba lako. Chora umbo la kiwanja, weka alama za mimea, na fuatilia afya yao.",
    "create.first.plot": "Unda Kiwanja cha Kwanza",
    "history": "Historia",
    "no.history": "Hakuna uchunguzi bado",
    "no.history.desc": "Historia ya uchunguzi itaonekana hapa",
    "all": "Zote",
    "crops": "Mazao",
    "livestock2": "Mifugo",
    "clear.history": "Futa Historia",
    "clear.history.confirm": "Una uhakika unataka kufuta rekodi zote za uchunguzi?",
    "delete.all.confirm": "Una uhakika unataka kufuta rekodi zote za uchunguzi?",
    "no.filter.diagnoses": "Hakuna uchunguzi katika jamii hii",
    "history.appears.here": "Historia ya uchunguzi itaonekana hapa",
    "land.subtitle": "Panga shamba, weka mimea, fuatilia afya",
    "grow.plan.reminder": "Kikumbusho cha Mpango wa Ukuaji",
    "plant": "Panda",
    "starting.today": "uanzayo leo",
    "error": "Kosa",
    "grow.plan.error": "Imeshindwa kutengeneza mpango wa ukuaji. Tafadhali jaribu tena.",
    "delete.all": "Futa Zote",
    "condition": "Hali",
    "severity": "Ukali",
    "confidence": "Uamuzi",
    "summary": "Muhtasari",
    "symptoms": "Dalili",
    "possible.causes": "Sababu Zinazowezekana",
    "treatments": "Matibabu",
    "prevention": "Kuzuia",
    "urgency": "Dharura",
    "your.description": "Maelezo Yako",
    "new.diagnosis2": "Uchunguzi Mpya",
    "delete.diagnosis": "Futa Uchunguzi",
    "delete.confirm": "Ondoa uchunguzi huu kutoka kwa historia yako?",
    "delete": "Futa",
    "weather": "Hali ya Hewa",
    "today": "Leo",
    "tomorrow": "Kesho",
    "humidity": "Unyevu",
    "wind": "Upepo",
    "rain.chance": "Nafasi ya Mvua",
    "uv.index": "Kiwango cha UV",
    "farming.advice": "Ushauri wa Kilimo",
    "share": "Sambaza",
    "share.via": "Sambaza kupitia",
    "copy": "Nakili",
    "copied": "Imenakiliwa",
    "whatsapp": "WhatsApp",
    "sms": "SMS",
    "share.diagnosis": "Sambaza Uchunguzi",
    "share.text": "Angalia uchunguzi huu kwenye Farmguard:",
    "settings": "Mipangilio",
    "language": "Lugha",
    "english": "Kiingereza",
    "swahili": "Kiswahili",
    "notifications": "Arifa",
    "enable.notifications": "Wezesha Arifa",
    "notification.reminders": "Vikumbusho vya Mpango wa Ukuaji",
    "notification.moon": "Matukio ya Mwezi",
    "notification.diagnosis": "Ufuatiliaji wa Uchunguzi",
    "near.me": "Karibu Nami",
    "sort.by": "Panga kwa",
    "price.low.high": "Bei: Chini kwenda Juu",
    "price.high.low": "Bei: Juu kwenda Chini",
    "distance": "Umbali",
    "newest": "Mpya Zaidi",
    "crop.database": "Hifadhi ya Mazao",
    "search.crops": "Tafuta mazao...",
    "crop.details": "Maelezo ya Mazao",
    "days.to.maturity": "Siku Hadi Kuvunwa",
    "spacing": "Nafasi",
    "water.needs": "Mahitaji ya Maji",
    "sun.needs": "Mahitaji ya Jua",
    "planting.depth": "Kina cha Kupanda",
    "seasons": "Majira",
    "regions": "Mikoa",
    "companion.plants": "Mimea Rafiki",
    "common.pests": "Wadudu Wanaoshambulia",
    "offline.saved": "Imehifadhiwa nje ya mtandao",
    "no.connection": "Hakuna muunganiko wa intaneti",
    "retry": "Jaribu tena",
    "offline.message": "Uko nje ya mtandao. Inaonyesha data iliyohifadhiwa.",
    "dismiss": "Ondoa",
    "watering": "Kumwagilia",
    "weeding": "Kupalilia",
    "fertilizing": "Kutia Mbolea",
    "harvesting": "Kuvuna",
    "pruning": "Kukata",
    "spraying": "Kunyunyizia",
    "soil.prep": "Kuandaa Udongo",
    "sowing": "Kupanda",
    "germination": "Kuchipuka",
    "vegetative": "Ukuaji wa Majani",
    "flowering": "Kuchanua",
    "fruiting": "Kuzaa Matunda",
  },
};

function getTranslation(lang: Language, key: string): string {
  return translations[lang][key] ?? key;
}

const I18nContext = createContext<I18nContextType>({
  lang: "en",
  setLang: async () => {},
  t: (key) => key,
});

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>("en");
  const [ready, setReady] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY)
      .then((v) => {
        if (v === "sw" || v === "en") setLangState(v);
      })
      .catch(() => {})
      .finally(() => setReady(true));
  }, []);

  const setLang = useCallback(async (l: Language) => {
    setLangState(l);
    await AsyncStorage.setItem(STORAGE_KEY, l);
  }, []);

  const t = useCallback((key: string) => getTranslation(lang, key), [lang]);

  if (!ready) return null;

  return (
    <I18nContext.Provider value={{ lang, setLang, t }}>
      {children}
    </I18nContext.Provider>
  );
}

export function useI18n() {
  return useContext(I18nContext);
}
