import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useState } from "react";

export type Language = "en" | "sw" | "fr" | "am";

interface I18nContextType {
  lang: Language;
  setLang: (l: Language) => Promise<void>;
  t: (key: string) => string;
}

const STORAGE_KEY = "@farmguard_language";

const translations: Record<Language, Record<string, string>> = {
  en: {
    "welcome.back": "Welcome back",
    "app.name": "Farmguard",
    "ai.diagnosis": "AI-Powered Diagnosis",
    "scan.farm": "Scan Your Farm",
    "scan.desc": "Take a photo or describe symptoms to identify diseases, pests, and conditions",
    "start.diagnosis": "Start Diagnosis",
    "total.scans": "Total Scans",
    "high.risk": "High Risk",
    "critical": "Critical",
    "quick.diagnose": "Quick Diagnose",
    "crop.issue": "Crop Issue",
    "crop.desc": "Diseases, pests, deficiencies",
    "livestock.issue": "Livestock Issue",
    "livestock.desc": "Health conditions, injuries",
    "recent.diagnoses": "Recent Diagnoses",
    "see.all": "See all",
    "no.diagnoses": "No diagnoses yet",
    "no.diagnoses.desc": "Tap 'Start Diagnosis' to scan your first crop or livestock",
    "new.diagnosis": "New Diagnosis",
    "photo.desc": "Photo + description gives the best results",
    "what.diagnosing": "What are you diagnosing?",
    "crop": "Crop",
    "livestock": "Livestock",
    "crop.type": "Crop type (optional)",
    "livestock.type": "Livestock type (optional)",
    "photo.optional": "Photo (optional but recommended)",
    "camera": "Camera",
    "gallery": "Gallery",
    "voice.input": "Voice Input",
    "describe.problem": "Describe the problem (optional)",
    "diagnose.ai": "Diagnose with AI",
    "diagnose.analyzing": "Analyzing...",
    "diagnose.disclaimer": "Powered by Claude AI. Results are advisory — consult an agricultural expert for critical issues.",
    "market.title": "Farmguard Market",
    "market.subtitle": "Fresh produce, direct from farmers",
    "shop": "Shop",
    "my.farm": "My Farm",
    "buy.requests": "Buy Requests",
    "search": "Search produce, location...",
    "register.farmer": "Register as Farmer",
    "sell.text": "Sell on Farmguard Market",
    "sell.desc": "Register your farm and start listing your fresh produce, livestock, and more to reach buyers near you.",
    "grow.planner": "Grow Planner",
    "moon.planting": "Moon-aware planting calendar for your season",
    "moon.today": "Moon Today",
    "upcoming.moon": "Upcoming Moon Events",
    "your.location": "Your Location",
    "use.my.location": "Use My Location",
    "detecting": "Detecting...",
    "enter.manually": "Enter Manually",
    "save": "Save",
    "cancel": "Cancel",
    "my.land": "My Land",
    "land.desc": "Design your plot, place plants, track health",
    "create.plot": "Create Plot",
    "agro.stores": "Agro Stores",
    "no.plots": "No land plots yet",
    "no.plots.desc": "Create a digital map of your farm. Draw the plot shape, drop plant markers, and track their health over time.",
    "create.first.plot": "Create First Plot",
    "history": "History",
    "no.history": "No diagnoses yet",
    "no.history.desc": "Your diagnosis history will appear here",
    "all": "All",
    "crops": "Crops",
    "livestock2": "Livestock",
    "clear.history": "Clear History",
    "clear.history.confirm": "Are you sure you want to delete all diagnosis records?",
    "delete.all.confirm": "Are you sure you want to delete all diagnosis records?",
    "no.filter.diagnoses": "No diagnoses in this category",
    "history.appears.here": "Your diagnosis history will appear here",
    "land.subtitle": "Design your plot, place plants, track health",
    "grow.plan.reminder": "Grow Plan Reminder",
    "plant": "Plant",
    "starting.today": "starting today",
    "error": "Error",
    "grow.plan.error": "Could not generate grow plan. Please try again.",
    "delete.all": "Delete All",
    "condition": "Condition",
    "severity": "Severity",
    "confidence": "Confidence",
    "summary": "Summary",
    "symptoms": "Symptoms",
    "possible.causes": "Possible Causes",
    "treatments": "Treatments",
    "prevention": "Prevention",
    "urgency": "Urgency",
    "your.description": "Your Description",
    "new.diagnosis2": "New Diagnosis",
    "delete.diagnosis": "Delete Diagnosis",
    "delete.confirm": "Remove this diagnosis from your history?",
    "delete": "Delete",
    "weather": "Weather",
    "today": "Today",
    "tomorrow": "Tomorrow",
    "humidity": "Humidity",
    "wind": "Wind",
    "rain.chance": "Rain Chance",
    "uv.index": "UV Index",
    "farming.advice": "Farming Advice",
    "share": "Share",
    "share.via": "Share via",
    "copy": "Copy",
    "copied": "Copied to clipboard",
    "whatsapp": "WhatsApp",
    "sms": "SMS",
    "share.diagnosis": "Share Diagnosis",
    "share.text": "Check this diagnosis on Farmguard:",
    "settings": "Settings",
    "language": "Language",
    "english": "English",
    "swahili": "Swahili",
    "french": "French",
    "amharic": "Amharic",
    "notifications": "Notifications",
    "enable.notifications": "Enable Notifications",
    "notification.reminders": "Grow Plan Reminders",
    "notification.moon": "Moon Events",
    "notification.diagnosis": "Diagnosis Follow-ups",
    "near.me": "Near Me",
    "sort.by": "Sort by",
    "price.low.high": "Price: Low to High",
    "price.high.low": "Price: High to Low",
    "distance": "Distance",
    "newest": "Newest",
    "crop.database": "Crop Database",
    "search.crops": "Search crops...",
    "crop.details": "Crop Details",
    "days.to.maturity": "Days to Maturity",
    "spacing": "Spacing",
    "water.needs": "Water Needs",
    "sun.needs": "Sun Needs",
    "planting.depth": "Planting Depth",
    "seasons": "Seasons",
    "regions": "Regions",
    "companion.plants": "Companion Plants",
    "common.pests": "Common Pests",
    "offline.saved": "Saved offline",
    "no.connection": "No internet connection",
    "retry": "Retry",
    "offline.message": "You're offline. Showing cached data.",
    "dismiss": "Dismiss",
    "watering": "Watering",
    "weeding": "Weeding",
    "fertilizing": "Fertilizing",
    "harvesting": "Harvesting",
    "pruning": "Pruning",
    "spraying": "Spraying",
    "soil.prep": "Soil Preparation",
    "sowing": "Sowing",
    "germination": "Germination",
    "vegetative": "Vegetative Growth",
    "flowering": "Flowering",
    "fruiting": "Fruiting",
    "appearance": "Appearance",
    "dark.mode": "Dark Mode",
    "light.mode": "Light Mode",
    "system.default": "System Default",
    "ask.followup": "Ask a Follow-up",
    "log.treatment": "Log Treatment",
    "treatment.log": "Treatment Log",
    "journal": "Farm Journal",
    "journal.desc": "Log daily farm activities",
    "add.entry": "Add Entry",
    "no.entries": "No journal entries yet",
    "observation": "Observation",
    "other": "Other",
    "price.trend": "Price Trend (30 days)",
  },
  sw: {
    "welcome.back": "Karibu tena",
    "app.name": "Farmguard",
    "ai.diagnosis": "Uchunguzi wa AI",
    "scan.farm": "Chunguza Shamba Lako",
    "scan.desc": "Piga picha au elezea dalili za magonjwa, wadudu na hali",
    "start.diagnosis": "Anza Uchunguzi",
    "total.scans": "Uchunguzi Wote",
    "high.risk": "Hatari Kubwa",
    "critical": "Muhimu",
    "quick.diagnose": "Uchunguzi wa Haraka",
    "crop.issue": "Mazao",
    "crop.desc": "Magonjwa, wadudu, ukosefu wa virutubisho",
    "livestock.issue": "Mifugo",
    "livestock.desc": "Hali za afya, majeraha",
    "recent.diagnoses": "Uchunguzi wa Hivi Karibuni",
    "see.all": "Tazama zote",
    "no.diagnoses": "Hakuna uchunguzi bado",
    "no.diagnoses.desc": "Gusa 'Anza Uchunguzi' kuchunguza mazao au mifugo wako wa kwanza",
    "new.diagnosis": "Uchunguzi Mpya",
    "photo.desc": "Picha + maelezo yanatoa matokeo bora",
    "what.diagnosing": "Unachunguza nini?",
    "crop": "Mazao",
    "livestock": "Mifugo",
    "crop.type": "Aina ya Mazao (si lazima)",
    "livestock.type": "Aina ya Mifugo (si lazima)",
    "photo.optional": "Picha (si lazima lakini inashauriwa)",
    "camera": "Kamera",
    "gallery": "Maktaba",
    "voice.input": "Sauti",
    "describe.problem": "Elezea tatizo (si lazima)",
    "diagnose.ai": "Chunguza kwa AI",
    "diagnose.analyzing": "Inachunguza...",
    "diagnose.disclaimer": "Inaendeshwa na Claude AI. Matokeo ni ya ushauri — tafuta mtaalamu wa kilimo kwa masuala muhimu.",
    "market.title": "Soko la Farmguard",
    "market.subtitle": "Chakula cha moja kwa moja kutoka kwa wakulima",
    "shop": "Soko",
    "my.farm": "Shamba Langu",
    "buy.requests": "Maombi ya Ununuzi",
    "search": "Tafuta mazao, eneo...",
    "register.farmer": "Jiandikishe kama Mkulima",
    "sell.text": "Uza kwenye Soko la Farmguard",
    "sell.desc": "Jiandikishe shamba lako na uanze kuweka mazao yako, mifugo, na zaidi ili kuwafikia wauzaji karibu nawe.",
    "grow.planner": "Mpangilio wa Ukuaji",
    "moon.planting": "Kalenda ya kupanda kwa mwezi",
    "moon.today": "Mwezi wa Leo",
    "upcoming.moon": "Matukio ya Mwezi Yajayo",
    "your.location": "Eneo Lako",
    "use.my.location": "Tumia Eneo Langu",
    "detecting": "Inagundua...",
    "enter.manually": "Weka kwa Mikono",
    "save": "Hifadhi",
    "cancel": "Ghairi",
    "my.land": "Ardhi Yangu",
    "land.desc": "Panga shamba, weka mimea, fuatilia afya",
    "create.plot": "Unda Kiwanja",
    "agro.stores": "Maduka ya Kilimo",
    "no.plots": "Hakuna viwanja bado",
    "no.plots.desc": "Tengeneza ramani ya kidigitali ya shamba lako.",
    "create.first.plot": "Unda Kiwanja cha Kwanza",
    "history": "Historia",
    "no.history": "Hakuna uchunguzi bado",
    "no.history.desc": "Historia ya uchunguzi itaonekana hapa",
    "all": "Zote",
    "crops": "Mazao",
    "livestock2": "Mifugo",
    "clear.history": "Futa Historia",
    "clear.history.confirm": "Una uhakika unataka kufuta rekodi zote za uchunguzi?",
    "delete.all.confirm": "Una uhakika unataka kufuta rekodi zote za uchunguzi?",
    "no.filter.diagnoses": "Hakuna uchunguzi katika jamii hii",
    "history.appears.here": "Historia ya uchunguzi itaonekana hapa",
    "land.subtitle": "Panga shamba, weka mimea, fuatilia afya",
    "grow.plan.reminder": "Kikumbusho cha Mpango wa Ukuaji",
    "plant": "Panda",
    "starting.today": "uanzayo leo",
    "error": "Kosa",
    "grow.plan.error": "Imeshindwa kutengeneza mpango wa ukuaji. Tafadhali jaribu tena.",
    "delete.all": "Futa Zote",
    "condition": "Hali",
    "severity": "Ukali",
    "confidence": "Uamuzi",
    "summary": "Muhtasari",
    "symptoms": "Dalili",
    "possible.causes": "Sababu Zinazowezekana",
    "treatments": "Matibabu",
    "prevention": "Kuzuia",
    "urgency": "Dharura",
    "your.description": "Maelezo Yako",
    "new.diagnosis2": "Uchunguzi Mpya",
    "delete.diagnosis": "Futa Uchunguzi",
    "delete.confirm": "Ondoa uchunguzi huu kutoka kwa historia yako?",
    "delete": "Futa",
    "weather": "Hali ya Hewa",
    "today": "Leo",
    "tomorrow": "Kesho",
    "humidity": "Unyevu",
    "wind": "Upepo",
    "rain.chance": "Nafasi ya Mvua",
    "uv.index": "Kiwango cha UV",
    "farming.advice": "Ushauri wa Kilimo",
    "share": "Sambaza",
    "share.via": "Sambaza kupitia",
    "copy": "Nakili",
    "copied": "Imenakiliwa",
    "whatsapp": "WhatsApp",
    "sms": "SMS",
    "share.diagnosis": "Sambaza Uchunguzi",
    "share.text": "Angalia uchunguzi huu kwenye Farmguard:",
    "settings": "Mipangilio",
    "language": "Lugha",
    "english": "Kiingereza",
    "swahili": "Kiswahili",
    "french": "Kifaransa",
    "amharic": "Kiamhari",
    "notifications": "Arifa",
    "enable.notifications": "Wezesha Arifa",
    "notification.reminders": "Vikumbusho vya Mpango wa Ukuaji",
    "notification.moon": "Matukio ya Mwezi",
    "notification.diagnosis": "Ufuatiliaji wa Uchunguzi",
    "near.me": "Karibu Nami",
    "sort.by": "Panga kwa",
    "price.low.high": "Bei: Chini kwenda Juu",
    "price.high.low": "Bei: Juu kwenda Chini",
    "distance": "Umbali",
    "newest": "Mpya Zaidi",
    "crop.database": "Hifadhi ya Mazao",
    "search.crops": "Tafuta mazao...",
    "crop.details": "Maelezo ya Mazao",
    "days.to.maturity": "Siku Hadi Kuvunwa",
    "spacing": "Nafasi",
    "water.needs": "Mahitaji ya Maji",
    "sun.needs": "Mahitaji ya Jua",
    "planting.depth": "Kina cha Kupanda",
    "seasons": "Majira",
    "regions": "Mikoa",
    "companion.plants": "Mimea Rafiki",
    "common.pests": "Wadudu Wanaoshambulia",
    "offline.saved": "Imehifadhiwa nje ya mtandao",
    "no.connection": "Hakuna muunganiko wa intaneti",
    "retry": "Jaribu tena",
    "offline.message": "Uko nje ya mtandao. Inaonyesha data iliyohifadhiwa.",
    "dismiss": "Ondoa",
    "watering": "Kumwagilia",
    "weeding": "Kupalilia",
    "fertilizing": "Kutia Mbolea",
    "harvesting": "Kuvuna",
    "pruning": "Kukata",
    "spraying": "Kunyunyizia",
    "soil.prep": "Kuandaa Udongo",
    "sowing": "Kupanda",
    "germination": "Kuchipuka",
    "vegetative": "Ukuaji wa Majani",
    "flowering": "Kuchanua",
    "fruiting": "Kuzaa Matunda",
    "appearance": "Muonekano",
    "dark.mode": "Hali ya Giza",
    "light.mode": "Hali ya Mwanga",
    "system.default": "Mfumo wa Kawaida",
    "ask.followup": "Uliza Swali",
    "log.treatment": "Rekodi Matibabu",
    "treatment.log": "Kumbukumbu ya Matibabu",
    "journal": "Jarida la Shamba",
    "journal.desc": "Rekodi shughuli za kila siku za shamba",
    "add.entry": "Ongeza Rekodi",
    "no.entries": "Hakuna rekodi bado",
    "observation": "Uchunguzi",
    "other": "Nyingine",
    "price.trend": "Mwenendo wa Bei (siku 30)",
  },
  fr: {
    "welcome.back": "Bon retour",
    "app.name": "Farmguard",
    "ai.diagnosis": "Diagnostic IA",
    "scan.farm": "Analysez votre ferme",
    "scan.desc": "Prenez une photo ou décrivez les symptômes pour identifier les maladies, ravageurs et conditions",
    "start.diagnosis": "Démarrer le diagnostic",
    "total.scans": "Analyses totales",
    "high.risk": "Risque élevé",
    "critical": "Critique",
    "quick.diagnose": "Diagnostic rapide",
    "crop.issue": "Problème de culture",
    "crop.desc": "Maladies, ravageurs, carences",
    "livestock.issue": "Problème de bétail",
    "livestock.desc": "Conditions de santé, blessures",
    "recent.diagnoses": "Diagnostics récents",
    "see.all": "Voir tout",
    "no.diagnoses": "Aucun diagnostic encore",
    "no.diagnoses.desc": "Appuyez sur 'Démarrer le diagnostic' pour analyser votre première culture ou bétail",
    "new.diagnosis": "Nouveau diagnostic",
    "photo.desc": "Photo + description donnent les meilleurs résultats",
    "what.diagnosing": "Que diagnostiquez-vous ?",
    "crop": "Culture",
    "livestock": "Bétail",
    "crop.type": "Type de culture (optionnel)",
    "livestock.type": "Type de bétail (optionnel)",
    "photo.optional": "Photo (optionnelle mais recommandée)",
    "camera": "Caméra",
    "gallery": "Galerie",
    "voice.input": "Voix",
    "describe.problem": "Décrivez le problème (optionnel)",
    "diagnose.ai": "Diagnostiquer avec l'IA",
    "diagnose.analyzing": "Analyse en cours...",
    "diagnose.disclaimer": "Propulsé par Claude IA. Les résultats sont indicatifs — consultez un expert agricole pour les cas critiques.",
    "market.title": "Marché Farmguard",
    "market.subtitle": "Produits frais, directement des agriculteurs",
    "shop": "Boutique",
    "my.farm": "Ma Ferme",
    "buy.requests": "Demandes d'achat",
    "search": "Rechercher produits, lieu...",
    "register.farmer": "S'inscrire comme agriculteur",
    "sell.text": "Vendre sur le marché Farmguard",
    "sell.desc": "Inscrivez votre ferme et commencez à lister vos produits frais pour atteindre les acheteurs proches de vous.",
    "grow.planner": "Planificateur de culture",
    "moon.planting": "Calendrier de plantation lunaire pour votre saison",
    "moon.today": "Lune aujourd'hui",
    "upcoming.moon": "Prochains événements lunaires",
    "your.location": "Votre localisation",
    "use.my.location": "Utiliser ma localisation",
    "detecting": "Détection...",
    "enter.manually": "Saisir manuellement",
    "save": "Enregistrer",
    "cancel": "Annuler",
    "my.land": "Mes terres",
    "land.desc": "Concevez votre parcelle, placez les plants, suivez la santé",
    "create.plot": "Créer une parcelle",
    "agro.stores": "Boutiques agricoles",
    "no.plots": "Aucune parcelle encore",
    "no.plots.desc": "Créez une carte numérique de votre ferme. Dessinez la forme de la parcelle, placez des marqueurs de plants et suivez leur santé.",
    "create.first.plot": "Créer la première parcelle",
    "history": "Historique",
    "no.history": "Aucun diagnostic encore",
    "no.history.desc": "Votre historique de diagnostics apparaîtra ici",
    "all": "Tous",
    "crops": "Cultures",
    "livestock2": "Bétail",
    "clear.history": "Effacer l'historique",
    "clear.history.confirm": "Voulez-vous vraiment supprimer tous les diagnostics ?",
    "delete.all.confirm": "Voulez-vous vraiment supprimer tous les diagnostics ?",
    "no.filter.diagnoses": "Aucun diagnostic dans cette catégorie",
    "history.appears.here": "Votre historique de diagnostics apparaîtra ici",
    "land.subtitle": "Concevez votre parcelle, placez les plants, suivez la santé",
    "grow.plan.reminder": "Rappel de plan de culture",
    "plant": "Planter",
    "starting.today": "à partir d'aujourd'hui",
    "error": "Erreur",
    "grow.plan.error": "Impossible de générer le plan de culture. Veuillez réessayer.",
    "delete.all": "Tout supprimer",
    "condition": "Condition",
    "severity": "Gravité",
    "confidence": "Confiance",
    "summary": "Résumé",
    "symptoms": "Symptômes",
    "possible.causes": "Causes possibles",
    "treatments": "Traitements",
    "prevention": "Prévention",
    "urgency": "Urgence",
    "your.description": "Votre description",
    "new.diagnosis2": "Nouveau diagnostic",
    "delete.diagnosis": "Supprimer le diagnostic",
    "delete.confirm": "Supprimer ce diagnostic de votre historique ?",
    "delete": "Supprimer",
    "weather": "Météo",
    "today": "Aujourd'hui",
    "tomorrow": "Demain",
    "humidity": "Humidité",
    "wind": "Vent",
    "rain.chance": "Probabilité de pluie",
    "uv.index": "Indice UV",
    "farming.advice": "Conseils agricoles",
    "share": "Partager",
    "share.via": "Partager via",
    "copy": "Copier",
    "copied": "Copié dans le presse-papier",
    "whatsapp": "WhatsApp",
    "sms": "SMS",
    "share.diagnosis": "Partager le diagnostic",
    "share.text": "Consultez ce diagnostic sur Farmguard :",
    "settings": "Paramètres",
    "language": "Langue",
    "english": "Anglais",
    "swahili": "Swahili",
    "french": "Français",
    "amharic": "Amharique",
    "notifications": "Notifications",
    "enable.notifications": "Activer les notifications",
    "notification.reminders": "Rappels de plan de culture",
    "notification.moon": "Événements lunaires",
    "notification.diagnosis": "Suivis de diagnostic",
    "near.me": "Près de moi",
    "sort.by": "Trier par",
    "price.low.high": "Prix : croissant",
    "price.high.low": "Prix : décroissant",
    "distance": "Distance",
    "newest": "Le plus récent",
    "crop.database": "Base de données des cultures",
    "search.crops": "Rechercher des cultures...",
    "crop.details": "Détails de la culture",
    "days.to.maturity": "Jours jusqu'à maturité",
    "spacing": "Espacement",
    "water.needs": "Besoins en eau",
    "sun.needs": "Besoins en soleil",
    "planting.depth": "Profondeur de plantation",
    "seasons": "Saisons",
    "regions": "Régions",
    "companion.plants": "Plantes compagnes",
    "common.pests": "Ravageurs courants",
    "offline.saved": "Enregistré hors ligne",
    "no.connection": "Pas de connexion internet",
    "retry": "Réessayer",
    "offline.message": "Vous êtes hors ligne. Affichage des données mises en cache.",
    "dismiss": "Ignorer",
    "watering": "Arrosage",
    "weeding": "Désherbage",
    "fertilizing": "Fertilisation",
    "harvesting": "Récolte",
    "pruning": "Taille",
    "spraying": "Pulvérisation",
    "soil.prep": "Préparation du sol",
    "sowing": "Semis",
    "germination": "Germination",
    "vegetative": "Croissance végétative",
    "flowering": "Floraison",
    "fruiting": "Fructification",
    "appearance": "Apparence",
    "dark.mode": "Mode sombre",
    "light.mode": "Mode clair",
    "system.default": "Paramètre système",
    "ask.followup": "Poser une question",
    "log.treatment": "Enregistrer le traitement",
    "treatment.log": "Journal de traitement",
    "journal": "Journal de ferme",
    "journal.desc": "Enregistrez les activités quotidiennes de la ferme",
    "add.entry": "Ajouter une entrée",
    "no.entries": "Aucune entrée encore",
    "observation": "Observation",
    "other": "Autre",
    "price.trend": "Tendance des prix (30 jours)",
  },
  am: {
    "welcome.back": "እንኳን ደህና መጡ",
    "app.name": "ፋርምጋርድ",
    "ai.diagnosis": "AI ምርመራ",
    "scan.farm": "እርሻዎን ይፈትሹ",
    "scan.desc": "ፎቶ ያንሱ ወይም ምልክቶቹን ይግለፁ",
    "start.diagnosis": "ምርመራ ጀምር",
    "total.scans": "ጠቅላላ ምርመራዎች",
    "high.risk": "ከፍተኛ አደጋ",
    "critical": "ወሳኝ",
    "quick.diagnose": "ፈጣን ምርመራ",
    "crop.issue": "የሰብል ችግር",
    "crop.desc": "ህመሞች፣ ተባዮች፣ ጉድለቶች",
    "livestock.issue": "የእንስሳት ችግር",
    "livestock.desc": "የጤና ሁኔታዎች፣ ጉዳቶች",
    "recent.diagnoses": "የቅርብ ጊዜ ምርመራዎች",
    "see.all": "ሁሉንም ይመልከቱ",
    "no.diagnoses": "እስካሁን ምርመራ የለም",
    "no.diagnoses.desc": "'ምርመራ ጀምር' ን ይጫኑ",
    "new.diagnosis": "አዲስ ምርመራ",
    "photo.desc": "ፎቶ + ማብራሪያ ምርጥ ውጤቶችን ይሰጣሉ",
    "what.diagnosing": "ምን እየመረመሩ ነው?",
    "crop": "ሰብል",
    "livestock": "እንስሳ",
    "crop.type": "የሰብል አይነት (አስፈላጊ አይደለም)",
    "livestock.type": "የእንስሳ አይነት (አስፈላጊ አይደለም)",
    "photo.optional": "ፎቶ (አስፈላጊ አይደለም ግን ይመከራል)",
    "camera": "ካሜራ",
    "gallery": "ጋለሪ",
    "voice.input": "ድምፅ",
    "describe.problem": "ችግሩን ይግለፁ (አስፈላጊ አይደለም)",
    "diagnose.ai": "በ AI ምርመራ ያድርጉ",
    "diagnose.analyzing": "እየተመረመረ ነው...",
    "diagnose.disclaimer": "በ Claude AI ይሰራል። ውጤቶቹ ምክር ናቸው — ለወሳኝ ጉዳዮች የግብርና ባለሙያ ያማክሩ።",
    "market.title": "ፋርምጋርድ ገበያ",
    "market.subtitle": "ትኩስ ምርት፣ ከገበሬዎች ቀጥታ",
    "shop": "ሱቅ",
    "my.farm": " እርሻዬ",
    "buy.requests": "የመግዣ ጥያቄዎች",
    "search": "ምርቶችን ፈልግ...",
    "register.farmer": "እንደ ገበሬ ይመዝገቡ",
    "sell.text": "በፋርምጋርድ ገበያ ይሸጡ",
    "sell.desc": "እርሻዎን ይመዝግቡ እና ምርቶቻቸውን ዝርዝር ያድርጉ።",
    "grow.planner": "የእድገት ዕቅድ",
    "moon.planting": "ለወቅቱ የጨረቃ ዕቅደ-ዘር ቀን መቁጠሪያ",
    "moon.today": "ዛሬ ጨረቃ",
    "upcoming.moon": "የሚመጡ የጨረቃ ክስተቶች",
    "your.location": "አካባቢዎ",
    "use.my.location": "አካባቢዬን ተጠቀም",
    "detecting": "እየፈለገ ነው...",
    "enter.manually": "በእጅ ያስገቡ",
    "save": "አስቀምጥ",
    "cancel": "ሰርዝ",
    "my.land": "መሬቴ",
    "land.desc": "ሴራዎን ዲዛይን ያድርጉ፣ ተክሎችን ያስቀምጡ፣ ጤናን ይከታተሉ",
    "create.plot": "ሴራ ፍጠር",
    "agro.stores": "የግብርና ሱቆች",
    "no.plots": "እስካሁን ሴራ የለም",
    "no.plots.desc": "የእርሻዎ ዲጂታል ካርታ ይፍጠሩ።",
    "create.first.plot": "የመጀመሪያ ሴራ ፍጠር",
    "history": "ታሪክ",
    "no.history": "እስካሁን ምርመራ የለም",
    "no.history.desc": "የምርመራ ታሪኮ እዚህ ይታያል",
    "all": "ሁሉም",
    "crops": "ሰብሎች",
    "livestock2": "እንስሳ",
    "clear.history": "ታሪክ ሰርዝ",
    "clear.history.confirm": "ሁሉንም የምርመራ መዛግብት መሰረዝ ይፈልጋሉ?",
    "delete.all.confirm": "ሁሉንም የምርመራ መዛግብት መሰረዝ ይፈልጋሉ?",
    "no.filter.diagnoses": "በዚህ ምድብ ምርመራ የለም",
    "history.appears.here": "የምርመራ ታሪኮ እዚህ ይታያል",
    "land.subtitle": "ሴራዎን ዲዛይን ያድርጉ፣ ተክሎችን ያስቀምጡ፣ ጤናን ይከታተሉ",
    "grow.plan.reminder": "የእድገት ዕቅድ አስታዋሽ",
    "plant": "ዘር",
    "starting.today": "ዛሬ ጀምሮ",
    "error": "ስህተት",
    "grow.plan.error": "የእድገት ዕቅድ መፍጠር አልተቻለም። እባክዎ እንደገና ይሞክሩ።",
    "delete.all": "ሁሉንም ሰርዝ",
    "condition": "ሁኔታ",
    "severity": "ክብደት",
    "confidence": "እምነት",
    "summary": "ማጠቃለያ",
    "symptoms": "ምልክቶች",
    "possible.causes": "ሊሆኑ የሚችሉ ምክንያቶች",
    "treatments": "ህክምናዎች",
    "prevention": "መከላከያ",
    "urgency": "አስቸኳይነት",
    "your.description": "ማብራሪያዎ",
    "new.diagnosis2": "አዲስ ምርመራ",
    "delete.diagnosis": "ምርመራ ሰርዝ",
    "delete.confirm": "ይህን ምርመራ ከታሪክዎ ያስወግዱ?",
    "delete": "ሰርዝ",
    "weather": "የአየር ሁኔታ",
    "today": "ዛሬ",
    "tomorrow": "ነገ",
    "humidity": "እርጥበት",
    "wind": "ንፋስ",
    "rain.chance": "የዝናብ ዕድል",
    "uv.index": "UV ጠቋሚ",
    "farming.advice": "የግብርና ምክር",
    "share": "አጋራ",
    "share.via": "በኩል አጋራ",
    "copy": "ቅዳ",
    "copied": "ወደ ቅብቅቦ ተቀድቷል",
    "whatsapp": "WhatsApp",
    "sms": "SMS",
    "share.diagnosis": "ምርመራ አጋራ",
    "share.text": "ይህን ምርመራ በፋርምጋርድ ይመልከቱ:",
    "settings": "ቅንጅቶች",
    "language": "ቋንቋ",
    "english": "እንግሊዝኛ",
    "swahili": "ስዋሂሊ",
    "french": "ፈረንሳይኛ",
    "amharic": "አማርኛ",
    "notifications": "ማሳወቂያዎች",
    "enable.notifications": "ማሳወቂያዎችን አንቃ",
    "notification.reminders": "የእድገት ዕቅድ አስታዋሾች",
    "notification.moon": "የጨረቃ ክስተቶች",
    "notification.diagnosis": "የምርመራ ክትትሎች",
    "near.me": "ቅርቤ",
    "sort.by": "በ ደርድር",
    "price.low.high": "ዋጋ: ዝቅ ወደ ከፍ",
    "price.high.low": "ዋጋ: ከፍ ወደ ዝቅ",
    "distance": "ርቀት",
    "newest": "አዲሱ",
    "crop.database": "የሰብል ዳታቤዝ",
    "search.crops": "ሰብሎችን ፈልግ...",
    "crop.details": "የሰብል ዝርዝሮች",
    "days.to.maturity": "ወደ ብስለት ቀናት",
    "spacing": "ክፍተት",
    "water.needs": "የውሃ ፍላጎቶች",
    "sun.needs": "የፀሐይ ፍላጎቶች",
    "planting.depth": "የዘርፋ ጥልቀት",
    "seasons": "ወቅቶች",
    "regions": "ክልሎች",
    "companion.plants": "ጓደኛ ተክሎች",
    "common.pests": "የተለመዱ ተባዮች",
    "offline.saved": "ከመስመር ውጪ ተቀምጧል",
    "no.connection": "የኢንተርኔት ግንኙነት የለም",
    "retry": "እንደገና ሞክር",
    "offline.message": "ከመስመር ውጪ ነዎት። የተቀመጡ ውሂቦችን እያሳየ ነው።",
    "dismiss": "አሰናብት",
    "watering": "ማጠጣት",
    "weeding": "አረም ማፅዳት",
    "fertilizing": "ማዳበሪያ",
    "harvesting": "መከር",
    "pruning": "መቁረጥ",
    "spraying": "መርጨት",
    "soil.prep": "የአፈር ዝግጅት",
    "sowing": "መዝራት",
    "germination": "ማብቀል",
    "vegetative": "የቅጠል እድገት",
    "flowering": "አበባ",
    "fruiting": "ፍሬ",
    "appearance": "ገጽታ",
    "dark.mode": "ጨለማ ሁነታ",
    "light.mode": "ብርሃን ሁነታ",
    "system.default": "የስርዓት ነባሪ",
    "ask.followup": "ጥያቄ ጠይቅ",
    "log.treatment": "ህክምና ይመዝግቡ",
    "treatment.log": "የህክምና ምዝገባ",
    "journal": "የእርሻ ማስታወሻ",
    "journal.desc": "የዕለት ተዕለት የእርሻ ሥራዎችን ይዝግቡ",
    "add.entry": "ግቤት ጨምር",
    "no.entries": "እስካሁን ግቤቶች የሉም",
    "observation": "ምልከታ",
    "other": "ሌላ",
    "price.trend": "የዋጋ አዝማሚያ (30 ቀናት)",
  },
};

function getTranslation(lang: Language, key: string): string {
  return translations[lang][key] ?? translations["en"][key] ?? key;
}

const I18nContext = createContext<I18nContextType>({
  lang: "en",
  setLang: async () => {},
  t: (key) => key,
});

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>("en");
  const [ready, setReady] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY)
      .then((v) => {
        if (v === "sw" || v === "en" || v === "fr" || v === "am") setLangState(v as Language);
      })
      .catch(() => {})
      .finally(() => setReady(true));
  }, []);

  const setLang = useCallback(async (l: Language) => {
    setLangState(l);
    await AsyncStorage.setItem(STORAGE_KEY, l);
  }, []);

  const t = useCallback((key: string) => getTranslation(lang, key), [lang]);

  if (!ready) return null;

  return (
    <I18nContext.Provider value={{ lang, setLang, t }}>
      {children}
    </I18nContext.Provider>
  );
}

export function useI18n() {
  return useContext(I18nContext);
}
