import { db, crops } from "@workspace/db";

async function seed() {
  const existing = await db.select({ count: crops.id }).from(crops);
  if (existing.length > 0) {
    console.log("Crops already seeded, skipping.");
    return;
  }

  const cropData = [
    { name: "Maize", category: "Cereals", family: "Poaceae", daysToMaturity: 90, daysToGermination: 7, spacingCm: 25, rowSpacingCm: 75, optimalTempMin: 18, optimalTempMax: 32, waterNeeds: "medium", sunNeeds: "full", seasons: "[\"spring\",\"summer\"]", regions: "[\"Kenya\",\"Uganda\",\"Tanzania\",\"Ethiopia\",\"Nigeria\",\"Ghana\"]", description: "Staple grain widely grown across Africa. High yielding and drought tolerant." },
    { name: "Beans", category: "Legumes", family: "Fabaceae", daysToMaturity: 60, daysToGermination: 8, spacingCm: 15, rowSpacingCm: 45, optimalTempMin: 15, optimalTempMax: 27, waterNeeds: "medium", sunNeeds: "full", seasons: "[\"spring\",\"summer\",\"autumn\"]", regions: "[\"Kenya\",\"Uganda\",\"Tanzania\",\"Ethiopia\",\"Rwanda\"]", description: "Nitrogen-fixing legume, excellent for intercropping with maize." },
    { name: "Tomato", category: "Vegetables", family: "Solanaceae", daysToMaturity: 75, daysToGermination: 7, spacingCm: 45, rowSpacingCm: 60, optimalTempMin: 18, optimalTempMax: 30, waterNeeds: "medium", sunNeeds: "full", seasons: "[\"spring\",\"summer\",\"autumn\"]", regions: "[\"Kenya\",\"Uganda\",\"Tanzania\",\"Ethiopia\",\"South Africa\"]", description: "High-value vegetable, popular for fresh market and processing." },
    { name: "Kale", category: "Vegetables", family: "Brassicaceae", daysToMaturity: 50, daysToGermination: 5, spacingCm: 30, rowSpacingCm: 45, optimalTempMin: 10, optimalTempMax: 25, waterNeeds: "medium", sunNeeds: "partial", seasons: "[\"spring\",\"autumn\",\"winter\"]", regions: "[\"Kenya\",\"Uganda\",\"Tanzania\",\"Rwanda\",\"Ethiopia\"]", description: "Nutrient-dense leafy green, staple in East African cuisine." },
    { name: "Spinach", category: "Vegetables", family: "Amaranthaceae", daysToMaturity: 40, daysToGermination: 5, spacingCm: 10, rowSpacingCm: 30, optimalTempMin: 10, optimalTempMax: 24, waterNeeds: "medium", sunNeeds: "partial", seasons: "[\"spring\",\"autumn\",\"winter\"]", regions: "[\"Kenya\",\"Uganda\",\"Tanzania\",\"Ethiopia\"]", description: "Fast-growing leafy green, excellent for small gardens." },
    { name: "Cabbage", category: "Vegetables", family: "Brassicaceae", daysToMaturity: 80, daysToGermination: 7, spacingCm: 45, rowSpacingCm: 60, optimalTempMin: 12, optimalTempMax: 24, waterNeeds: "high", sunNeeds: "full", seasons: "[\"spring\",\"autumn\"]", regions: "[\"Kenya\",\"Uganda\",\"Tanzania\",\"Ethiopia\",\"South Africa\"]", description: "Popular market vegetable, high water requirement." },
    { name: "Potato", category: "Vegetables", family: "Solanaceae", daysToMaturity: 90, daysToGermination: 14, spacingCm: 30, rowSpacingCm: 75, optimalTempMin: 15, optimalTempMax: 20, waterNeeds: "medium", sunNeeds: "full", seasons: "[\"spring\",\"autumn\"]", regions: "[\"Ethiopia\",\"Kenya\",\"Uganda\",\"Tanzania\",\"Rwanda\"]", description: "Important tuber crop, staple in highland regions." },
    { name: "Rice", category: "Cereals", family: "Poaceae", daysToMaturity: 120, daysToGermination: 10, spacingCm: 20, rowSpacingCm: 30, optimalTempMin: 20, optimalTempMax: 35, waterNeeds: "high", sunNeeds: "full", seasons: "[\"summer\"]", regions: "[\"Tanzania\",\"Uganda\",\"Madagascar\",\"Nigeria\"]", description: "Major staple grown in flooded paddies or upland systems." },
    { name: "Sorghum", category: "Cereals", family: "Poaceae", daysToMaturity: 100, daysToGermination: 7, spacingCm: 15, rowSpacingCm: 75, optimalTempMin: 25, optimalTempMax: 35, waterNeeds: "low", sunNeeds: "full", seasons: "[\"spring\",\"summer\"]", regions: "[\"Kenya\",\"Ethiopia\",\"Uganda\",\"Tanzania\",\"Nigeria\"]", description: "Drought-resistant grain, excellent for arid regions." },
    { name: "Millet", category: "Cereals", family: "Poaceae", daysToMaturity: 70, daysToGermination: 5, spacingCm: 10, rowSpacingCm: 45, optimalTempMin: 25, optimalTempMax: 35, waterNeeds: "low", sunNeeds: "full", seasons: "[\"spring\",\"summer\"]", regions: "[\"Kenya\",\"Uganda\",\"Tanzania\",\"Ethiopia\",\"Nigeria\"]", description: "Hardy grain, grows well in poor soils and low rainfall." },
    { name: "Groundnut", category: "Legumes", family: "Fabaceae", daysToMaturity: 120, daysToGermination: 10, spacingCm: 15, rowSpacingCm: 45, optimalTempMin: 22, optimalTempMax: 30, waterNeeds: "low", sunNeeds: "full", seasons: "[\"spring\",\"summer\"]", regions: "[\"Nigeria\",\"Ghana\",\"Uganda\",\"Tanzania\",\"Kenya\"]", description: "Oil and protein-rich legume, grows well in sandy soils." },
    { name: "Soybean", category: "Legumes", family: "Fabaceae", daysToMaturity: 100, daysToGermination: 7, spacingCm: 10, rowSpacingCm: 50, optimalTempMin: 20, optimalTempMax: 30, waterNeeds: "medium", sunNeeds: "full", seasons: "[\"spring\",\"summer\"]", regions: "[\"Uganda\",\"Tanzania\",\"Kenya\",\"Ethiopia\",\"Nigeria\"]", description: "High-protein legume, excellent for improving soil fertility." },
    { name: "Banana", category: "Fruits", family: "Musaceae", daysToMaturity: 300, daysToGermination: 0, spacingCm: 300, rowSpacingCm: 300, optimalTempMin: 20, optimalTempMax: 30, waterNeeds: "high", sunNeeds: "full", seasons: "[\"year-round\"]", regions: "[\"Uganda\",\"Tanzania\",\"Kenya\",\"Rwanda\",\"Ethiopia\"]", description: "Important cash and food crop, grown year-round in tropics." },
    { name: "Mango", category: "Fruits", family: "Anacardiaceae", daysToMaturity: 150, daysToGermination: 0, spacingCm: 800, rowSpacingCm: 800, optimalTempMin: 24, optimalTempMax: 30, waterNeeds: "medium", sunNeeds: "full", seasons: "[\"summer\"]", regions: "[\"Kenya\",\"Tanzania\",\"Uganda\",\"Nigeria\",\"Ghana\"]", description: "High-value fruit tree, excellent for export markets." },
    { name: "Avocado", category: "Fruits", family: "Lauraceae", daysToMaturity: 200, daysToGermination: 0, spacingCm: 700, rowSpacingCm: 700, optimalTempMin: 15, optimalTempMax: 25, waterNeeds: "medium", sunNeeds: "full", seasons: "[\"year-round\"]", regions: "[\"Kenya\",\"Tanzania\",\"Uganda\",\"Ethiopia\"]", description: "Premium export crop, high demand in global markets." },
    { name: "Coffee", category: "Cash Crops", family: "Rubiaceae", daysToMaturity: 365, daysToGermination: 0, spacingCm: 200, rowSpacingCm: 200, optimalTempMin: 15, optimalTempMax: 24, waterNeeds: "medium", sunNeeds: "partial", seasons: "[\"year-round\"]", regions: "[\"Ethiopia\",\"Kenya\",\"Tanzania\",\"Uganda\",\"Rwanda\"]", description: "Major export crop for East Africa, grown in highlands." },
    { name: "Tea", category: "Cash Crops", family: "Theaceae", daysToMaturity: 365, daysToGermination: 0, spacingCm: 120, rowSpacingCm: 120, optimalTempMin: 18, optimalTempMax: 30, waterNeeds: "high", sunNeeds: "partial", seasons: "[\"year-round\"]", regions: "[\"Kenya\",\"Uganda\",\"Tanzania\",\"Rwanda\"]", description: "Important export crop, thrives in high rainfall areas." },
    { name: "Cassava", category: "Roots", family: "Euphorbiaceae", daysToMaturity: 300, daysToGermination: 14, spacingCm: 100, rowSpacingCm: 100, optimalTempMin: 25, optimalTempMax: 35, waterNeeds: "low", sunNeeds: "full", seasons: "[\"spring\",\"summer\",\"autumn\"]", regions: "[\"Nigeria\",\"Tanzania\",\"Uganda\",\"Kenya\",\"Ghana\"]", description: "Drought-tolerant root crop, staple in many regions." },
    { name: "Sweet Potato", category: "Roots", family: "Convolvulaceae", daysToMaturity: 120, daysToGermination: 10, spacingCm: 30, rowSpacingCm: 75, optimalTempMin: 20, optimalTempMax: 30, waterNeeds: "medium", sunNeeds: "full", seasons: "[\"spring\",\"summer\",\"autumn\"]", regions: "[\"Uganda\",\"Tanzania\",\"Kenya\",\"Ethiopia\",\"Rwanda\"]", description: "Nutrient-rich root vegetable, fast growing and high yielding." },
    { name: "Onion", category: "Vegetables", family: "Amaryllidaceae", daysToMaturity: 120, daysToGermination: 10, spacingCm: 10, rowSpacingCm: 30, optimalTempMin: 13, optimalTempMax: 24, waterNeeds: "medium", sunNeeds: "full", seasons: "[\"spring\",\"autumn\"]", regions: "[\"Kenya\",\"Tanzania\",\"Ethiopia\",\"Uganda\",\"South Africa\"]", description: "Essential cooking ingredient, high value in local markets." },
  ];

  for (const crop of cropData) {
    await db.insert(crops).values(crop);
  }
  console.log(`Seeded ${cropData.length} crops.`);
}

seed().catch(console.error).finally(() => process.exit(0));
